#!/bin/bash

if [ ! -f "/etc/arch-release" ]; then
    echo "This script only works on Arch Linux" 1>&2
    exit 1
fi

set -e

function log() {
    echo -e "\033[1;33m$1\033[0m"
}

function yay_install() {
    log "Installing $1"
    yay -Sq --noconfirm --needed "$1"
}

log "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:piotrek-szczygiel/dotfiles-wsl.git"

yay_install bat
yay_install diff-so-fancy
yay_install exa
yay_install fd
yay_install fish
yay_install neovim
yay_install openssh
yay_install python-pynvim
yay_install ripgrep

log "Installing neovim plugins"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'

log "Installing fish plugins"
fish -c fisher

log "Done!"
log "Issue 'chsh -s /usr/bin/fish' to change your shell to fish"

