#!/bin/bash

if [ ! -f "/etc/arch-release" ]; then
    echo "This script only works on Arch Linux" 1>&2
    exit 1
fi

set -e

function echo_yellow() {
    echo -e "\033[1;33m$1\033[0m"
}

function pacman_install() {
    echo_yellow "Installing $1"
    sudo pacman -Sq --noconfirm "$1"
}

function yay_install() {
    echo_yellow "Installing $1"
    yay -Sq --noconfirm "$1"
}

echo_yellow "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:piotrek-szczygiel/dotfiles-wsl.git"

echo_yellow "Enabling colored output"
sudo sed -i '/Color/s/^#//' /etc/pacman.conf

echo_yellow "Removing fakeroot-tcp"
sudo pacman -Rns --noconfirm fakeroot-tcp || true

echo_yellow "Updating system"
sudo pacman -Syuq --noconfirm

yay_install bat
yay_install diff-so-fancy
yay_install exa
yay_install fd
yay_install fish
yay_install fontconfig
yay_install kitty
yay_install neovim
yay_install openssh
yay_install python-pynvim
yay_install ripgrep
yay_install starship-bin

echo_yellow "Installing neovim plugins"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'

echo_yellow "Adding Windows fonts"
sudo tee /etc/fonts/local.conf > /dev/null <<EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <dir>/mnt/c/Windows/Fonts</dir>
</fontconfig>
EOF
